### ISSUE TITLE
partyGet endpoint doesnt return members (at least not the creator)

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#12]
It returns this object:
![grafik](https://github.com/Coflnet/SongVoter/assets/58751503/54e4c52a-f870-4eb0-a091-4b57d0248ca7)

I as the creator should be included there

**Comment by Ekwav** [comment]
the creator is now returned in the special property `ownerId` he is logically put as that because that allows him to manage the party

**Comment by Ekwav** [comment]
closed because no reponse
