### ISSUE TITLE
Add option to force a spotify song

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#19]
What exactly should happen, if the next song that is supposed to be played, is a youtube song, but the app is currently not open?
My idea would be to add a option "onlyBackground" to the partyNextSongGet endpoint, which forces a song from a provider that can be played in the background (currently only spotify).

**Comment by Ekwav** [comment]
did you run the app in the background? To my knowledge it would be stopped by android and you can't play spotify either

**Comment by matthias-luger** [comment]
Yes, I do handle the spotify stuff in a background service

**Comment by Ekwav** [comment]
So I  added an option to create party that allows you to specify what platforms are supported. Does that satisfy your requirement?

**Comment by matthias-luger** [comment]
yes
