### ISSUE TITLE
Add songs to playlist returns HTTP 400

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#28]
`/lists/{listId}/songs` always returns HTTP 400

**Comment by Ekwav** [comment]
Assuming you mean the post request I can not reproduce that and have no found logs of a failing one. My I ask for the error response?

**Comment by matthias-luger** [comment]
`{"response":{"type":"default","status":400,"ok":false,"statusText":"","headers":{"map":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"7fbf3ee9ec961536-DUS","content-length":"46","content-type":"application/json; charset=utf-8","date":"Thu, 24 Aug 2023 23:06:26 GMT","nel":"{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}","report-to":"{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=%2Bg%2FBp7rHmB4VYQKFjKqsKa0LlVt6Zk%2FLCLm7pvU%2BQntZvX23MKa0c63%2BQttTIcs3e%2Bg5FqY8uqlRQwqQfHcVt1bNoHk2fMFGlqmjyJC8vMnxbtmPEDpVkD4it0RKOcQPThY%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}","server":"cloudflare"}},"url":"https://songvoter.party/lists/qD/songs","bodyUsed":false,"_bodyInit":{"_data":{"size":46,"offset":0,"blobId":"a6f0d3dd-4798-43ea-b2a3-4fbeb76fcefa","__collector":{}}},"_bodyBlob":{"_data":{"size":46,"offset":0,"blobId":"a6f0d3dd-4798-43ea-b2a3-4fbeb76fcefa","__collector":{}}}},"name":"ResponseError"}`

**Comment by Ekwav** [comment]
endpoint was used wrong
