### ISSUE TITLE
Add endpoint to use the authorization code for google

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#32]
Add a endpoint similar to Spotify that accepts the authorization code for the Google Login.

**Comment by Ekwav** [comment]
Added /auth/anonymous do you still want a code auth for google?

**Comment by matthias-luger** [comment]
For now, I dont think so. I only need the code auth when we
A) Want to add or even force a Google login for the web UI
or
B) Want to add things that require a Google login to the web UI
