### ISSUE TITLE
Search returns HTTP 500

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#33]
The search endpoint started to return HTTP 500.
Logs:
![grafik](https://github.com/Coflnet/SongVoter/assets/58751503/9ba84795-d5fe-414d-ad10-f9e582ee45ba)

**Comment by Ekwav** [comment]
I am afraid I am currently unable to reproduce that. Is that still an issue?

**Comment by matthias-luger** [comment]
Currently not, no. It seems to be in intervals though.
It didn't work for like 5 minutes, then it started working again. And repeat.
