### ISSUE TITLE
Allow multiple platforms

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#34]
Allow multiple supported platforms to be set in the `/party` POST endpoint.
Also allow multiple supported platforms in the `/songs/search` endpoint.

**Comment by matthias-luger** [comment]
It is still not possible to select multiple values in these endpoints:
![grafik](https://github.com/Coflnet/SongVoter/assets/58751503/569ec36e-bd52-4d1e-890e-872ee00c44e2)

**Comment by Ekwav** [comment]
its possible, can be specified like this `/api/party?Name=mark&SupportedPlatforms=youtube,spotify` alternatively 3 (combne the enum value)

**Comment by matthias-luger** [comment]
@Ekwav 
Well, seems like Swagger doesnt support the [Flags] annotation.
Either I make the API call manually, or you find a way, so I (and my swagger client) can call it with multiple values.
Wouldn't it be possible to just accept an Array of the enum? You can then just add them together and cast it back to the flagged enum, right?
