### ISSUE TITLE
Creating a party returns HTTP 400

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#36]
Trying to create a party now returns HTTP 400. I guess this has something to do with the new supportedPlatforms.

![grafik](https://github.com/Coflnet/SongVoter/assets/58751503/11ac035e-955e-43a6-ab24-700df472cf5f)

**Comment by Ekwav** [comment]
can't reproduce, whats the response? Are you already in a party?

**Comment by matthias-luger** [comment]
@Ekwav 
Url: https://songvoter.party/api/party?Name=t&SupportedPlatforms=spotify
No body
Response: HTTP 400
Still don't know how to access the response body. So I can't tell you if there is one or whats in it

**Comment by matthias-luger** [comment]
![grafik](https://github.com/Coflnet/SongVoter/assets/58751503/28f6438d-9fbb-49ab-8d9e-f77f4be31414)

**Comment by Ekwav** [comment]
What do you get when you try to load the party info?

**Comment by matthias-luger** [comment]
Hm, seems like I actually get the party. Would have worked before but now my UI caches if I am in a party and because the request failed it assumes I am not in a party.
=> It shows the Create Party button
