### ISSUE TITLE
User Info Endpoint returns HTTP 500

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SongVoter#41]
The /user/info endpoint sometimes returns HTTP 500
![grafik](https://github.com/Coflnet/SongVoter/assets/58751503/cd58236f-b46c-480b-ad17-637368e4788d)
(Image is also in the songvoter discord channel)

**Comment by Ekwav** [comment]
Thanks, that happened when the user was deleted, I now return a correct(er) error
